Added skipFile logic

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -5,190 +5,192 @@ on:
     branches:
       - master
       - mlh41tests
-
+  push:
+    branches:
+      - mlh41tests
 concurrency:
   group: shared-integration-tests
   cancel-in-progress: false
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-
-      - name: Set up JDK 1.8
-        uses: actions/setup-java@v1
-        with:
-          java-version: 1.8
-
-      - name: Cache Maven packages
-        uses: actions/cache@v3
-        with:
-          path: ~/.m2
-          key: ${{ runner.os }}-m2-${{ hashFiles('**/build.sh') }}
-          restore-keys: ${{ runner.os }}-m2
-
-      - name: Get branch name
-        run: |
-          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
-          echo BRANCH_NAME=${GITHUB_REF#refs/heads/}
-
-      - name: Create Maven Settings
-        uses: s4u/maven-settings-action@v2.8.0
-        with:
-          servers: |
-            [{
-                "id": "github",
-                "username": "atlan-ci",
-                "password": "${{ secrets.ORG_PAT_GITHUB }}"
-            }]
-
-      - name: Build with Maven
-        run: |
-          branch_name=${{ env.BRANCH_NAME }}
-          if [[ $branch_name == 'main' || $branch_name == 'master' || $branch_name == 'lineageondemand' ]]
-          then
-              echo "build without dashboard"
-              chmod +x ./build.sh && ./build.sh build_without_dashboard
-          else
-              echo "build with dashboard"
-              chmod +x ./build.sh && ./build.sh
-          fi
-
-      - name: Get Repository Name
-        run: echo "REPOSITORY_NAME=`echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//"`" >> $GITHUB_ENV
-        shell: bash
-
-      - name: Get version tag
-        # run: echo "##[set-output name=version;]$(echo `git ls-remote https://${{ secrets.ORG_PAT_GITHUB }}@github.com/atlanhq/${REPOSITORY_NAME}.git ${{ env.BRANCH_NAME }} | awk '{ print $1}' | cut -c1-7`)abcd"
-        run: |
-          echo "VERSION=$(git ls-remote https://${{ secrets.ORG_PAT_GITHUB }}@github.com/atlanhq/${REPOSITORY_NAME}.git ${{ env.BRANCH_NAME }} | awk '{ print $1}' | cut -c1-7 | head -n 1)abcd"
-          echo "VERSION=$(git ls-remote https://${{ secrets.ORG_PAT_GITHUB }}@github.com/atlanhq/${REPOSITORY_NAME}.git ${{ env.BRANCH_NAME }} | awk '{ print $1}' | cut -c1-7 | tr -d '[:space:]')abcd"
-          echo "VERSION=$(git ls-remote https://${{ secrets.ORG_PAT_GITHUB }}@github.com/atlanhq/${REPOSITORY_NAME}.git ${{ env.BRANCH_NAME }} | awk '{ print $1}' | cut -c1-7 | tr -d '[:space:]')abcd" >> $GITHUB_ENV
-
-      - name: Get commit ID
-        run: echo "COMMIT_ID=$(echo ${GITHUB_SHA} | cut -c1-7)abcd" >> $GITHUB_ENV
-
-      - name: Set up Buildx
-        id: buildx
-        uses: docker/setup-buildx-action@v1
-
-      - name: Login to GitHub Registry
-        uses: docker/login-action@v1
-        with:
-          registry: ghcr.io
-          username: $GITHUB_ACTOR
-          password: ${{ secrets.ORG_PAT_GITHUB }}
-
-      - name: Build and push
-        id: docker_build
-        uses: docker/build-push-action@v2
-        with:
-          context: .
-          file: ./Dockerfile
-          no-cache: true
-          sbom: true
-          provenance: true
-          push: true
-          tags: |
-            ghcr.io/atlanhq/${{ github.event.repository.name }}-${{ env.BRANCH_NAME }}:latest
-            ghcr.io/atlanhq/${{ github.event.repository.name }}-${{ env.BRANCH_NAME }}:${{ env.COMMIT_ID }}
-
-      - name: Scan Image
-        uses: aquasecurity/trivy-action@master
-        with:
-          image-ref: 'ubuntu:18.04'
-          vuln-type: 'os,library'
-          format: 'sarif'
-          output: 'trivy-image-results.sarif'
-
-      - name: Upload Trivy scan results to GitHub Security tab
-        uses: github/codeql-action/upload-sarif@v2.1.33
-        with:
-          sarif_file: 'trivy-image-results.sarif'
-
-
-  set-image-tag:
-    runs-on: metastore-sh-runner
-    needs: build
-    steps:
-      - name: Get commit ID
-        run: echo "COMMIT_ID=$(echo ${GITHUB_SHA} | cut -c1-7)abcd" >> $GITHUB_ENV
-
-      - name: Get Repository Name
-        run: echo "REPOSITORY_NAME=`echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//"`" >> $GITHUB_ENV
-        shell: bash
-
-      - name: Get branch name
-        run: |
-          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
-          echo BRANCH_NAME=${GITHUB_REF#refs/heads/}
-
-      - name: Set Image Tag
-        run: |
-          IMAGE_TAG="ghcr.io/atlanhq/${{ github.event.repository.name }}-${{ env.BRANCH_NAME }}:${{ env.COMMIT_ID }}"
-          
-          echo "Image Tag: ${IMAGE_TAG}"  # Print out the image tag
-          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV  # Store in GITHUB_ENV
-
-      - name: Verify kubectl Installation
-        run: |
-          if ! command -v kubectl &> /dev/null; then
-            echo "kubectl is not installed! Installing..."
-            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
-            chmod +x kubectl
-            sudo mv kubectl /usr/local/bin/
-          else
-            echo "kubectl is installed!"
-          fi
-          kubectl version --client
-
-      - name: Verify Kubernetes Connection
-        run: |
-          echo "Checking if kubectl can connect to the cluster..."
-          kubectl get namespaces
-      - name: Check Pods in namespaces
-        run: |
-          kubectl get pods -n sh-runner
-          kubectl get pods -n atlas
-      - name: Set atlas image
-        run: |
-          echo "Updating StatefulSet 'atlas' with image: ${{ env.IMAGE_TAG }}"
-          kubectl set image statefulset/atlas -n atlas atlas-main=${{ env.IMAGE_TAG }}
-
-  wait-for-deployment:
-    needs: set-image-tag
-    runs-on: ubuntu-latest
-    steps:
-      - name: Get commit ID
-        run: echo "COMMIT_ID=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
-
-      - name: Wait for Matching Revision
-        run: |
-          MAX_RETRIES=30  # Set maximum number of retries
-          SLEEP_TIME=60  # Time in seconds between retries
-
-          for i in $(seq 1 $MAX_RETRIES); do
-              echo "Attempt $i: Checking API for matching commit ID..."
-
-              REVISION=$(curl --silent --location 'https://gcpotel.atlan.com/api/meta/admin/version' \
-                --header "Authorization: Bearer $(curl --silent --location 'https://gcpotel.atlan.com/auth/realms/default/protocol/openid-connect/token' \
-                  --header 'Content-Type: application/x-www-form-urlencoded' \
-                  --data-urlencode 'client_id=atlan-argo' \
-                  --data-urlencode 'grant_type=client_credentials' \
-                  --data-urlencode "client_secret=${{ secrets.ATLAN_ARGO_CLIENT_SECRET }}" | jq -r '.access_token')" | jq -r '.Revision' | cut -c1-7)
-
-              echo "Fetched Revision: $REVISION"
-              echo "Expected Commit ID: ${{ env.COMMIT_ID }}"
-              if [[ "$REVISION" == "${{ env.COMMIT_ID }}" ]]; then
-                  echo "✅ Revision matches commit ID! Proceeding to the next step..."
-                  exit 0
-              fi
-              echo "🔄 No match yet. Retrying in $SLEEP_TIME seconds..."
-              sleep $SLEEP_TIME
-          done
-          echo "❌ ERROR: Max retries reached. Commit ID did not match the revision."
-          exit 1
+#  build:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v2
+#
+#      - name: Set up JDK 1.8
+#        uses: actions/setup-java@v1
+#        with:
+#          java-version: 1.8
+#
+#      - name: Cache Maven packages
+#        uses: actions/cache@v3
+#        with:
+#          path: ~/.m2
+#          key: ${{ runner.os }}-m2-${{ hashFiles('**/build.sh') }}
+#          restore-keys: ${{ runner.os }}-m2
+#
+#      - name: Get branch name
+#        run: |
+#          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
+#          echo BRANCH_NAME=${GITHUB_REF#refs/heads/}
+#
+#      - name: Create Maven Settings
+#        uses: s4u/maven-settings-action@v2.8.0
+#        with:
+#          servers: |
+#            [{
+#                "id": "github",
+#                "username": "atlan-ci",
+#                "password": "${{ secrets.ORG_PAT_GITHUB }}"
+#            }]
+#
+#      - name: Build with Maven
+#        run: |
+#          branch_name=${{ env.BRANCH_NAME }}
+#          if [[ $branch_name == 'main' || $branch_name == 'master' || $branch_name == 'lineageondemand' ]]
+#          then
+#              echo "build without dashboard"
+#              chmod +x ./build.sh && ./build.sh build_without_dashboard
+#          else
+#              echo "build with dashboard"
+#              chmod +x ./build.sh && ./build.sh
+#          fi
+#
+#      - name: Get Repository Name
+#        run: echo "REPOSITORY_NAME=`echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//"`" >> $GITHUB_ENV
+#        shell: bash
+#
+#      - name: Get version tag
+#        # run: echo "##[set-output name=version;]$(echo `git ls-remote https://${{ secrets.ORG_PAT_GITHUB }}@github.com/atlanhq/${REPOSITORY_NAME}.git ${{ env.BRANCH_NAME }} | awk '{ print $1}' | cut -c1-7`)abcd"
+#        run: |
+#          echo "VERSION=$(git ls-remote https://${{ secrets.ORG_PAT_GITHUB }}@github.com/atlanhq/${REPOSITORY_NAME}.git ${{ env.BRANCH_NAME }} | awk '{ print $1}' | cut -c1-7 | head -n 1)abcd"
+#          echo "VERSION=$(git ls-remote https://${{ secrets.ORG_PAT_GITHUB }}@github.com/atlanhq/${REPOSITORY_NAME}.git ${{ env.BRANCH_NAME }} | awk '{ print $1}' | cut -c1-7 | tr -d '[:space:]')abcd"
+#          echo "VERSION=$(git ls-remote https://${{ secrets.ORG_PAT_GITHUB }}@github.com/atlanhq/${REPOSITORY_NAME}.git ${{ env.BRANCH_NAME }} | awk '{ print $1}' | cut -c1-7 | tr -d '[:space:]')abcd" >> $GITHUB_ENV
+#
+#      - name: Get commit ID
+#        run: echo "COMMIT_ID=$(echo ${GITHUB_SHA} | cut -c1-7)abcd" >> $GITHUB_ENV
+#
+#      - name: Set up Buildx
+#        id: buildx
+#        uses: docker/setup-buildx-action@v1
+#
+#      - name: Login to GitHub Registry
+#        uses: docker/login-action@v1
+#        with:
+#          registry: ghcr.io
+#          username: $GITHUB_ACTOR
+#          password: ${{ secrets.ORG_PAT_GITHUB }}
+#
+#      - name: Build and push
+#        id: docker_build
+#        uses: docker/build-push-action@v2
+#        with:
+#          context: .
+#          file: ./Dockerfile
+#          no-cache: true
+#          sbom: true
+#          provenance: true
+#          push: true
+#          tags: |
+#            ghcr.io/atlanhq/${{ github.event.repository.name }}-${{ env.BRANCH_NAME }}:latest
+#            ghcr.io/atlanhq/${{ github.event.repository.name }}-${{ env.BRANCH_NAME }}:${{ env.COMMIT_ID }}
+#
+#      - name: Scan Image
+#        uses: aquasecurity/trivy-action@master
+#        with:
+#          image-ref: 'ubuntu:18.04'
+#          vuln-type: 'os,library'
+#          format: 'sarif'
+#          output: 'trivy-image-results.sarif'
+#
+#      - name: Upload Trivy scan results to GitHub Security tab
+#        uses: github/codeql-action/upload-sarif@v2.1.33
+#        with:
+#          sarif_file: 'trivy-image-results.sarif'
+#
+#
+#  set-image-tag:
+#    runs-on: metastore-sh-runner
+#    needs: build
+#    steps:
+#      - name: Get commit ID
+#        run: echo "COMMIT_ID=$(echo ${GITHUB_SHA} | cut -c1-7)abcd" >> $GITHUB_ENV
+#
+#      - name: Get Repository Name
+#        run: echo "REPOSITORY_NAME=`echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//"`" >> $GITHUB_ENV
+#        shell: bash
+#
+#      - name: Get branch name
+#        run: |
+#          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
+#          echo BRANCH_NAME=${GITHUB_REF#refs/heads/}
+#
+#      - name: Set Image Tag
+#        run: |
+#          IMAGE_TAG="ghcr.io/atlanhq/${{ github.event.repository.name }}-${{ env.BRANCH_NAME }}:${{ env.COMMIT_ID }}"
+#
+#          echo "Image Tag: ${IMAGE_TAG}"  # Print out the image tag
+#          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV  # Store in GITHUB_ENV
+#
+#      - name: Verify kubectl Installation
+#        run: |
+#          if ! command -v kubectl &> /dev/null; then
+#            echo "kubectl is not installed! Installing..."
+#            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
+#            chmod +x kubectl
+#            sudo mv kubectl /usr/local/bin/
+#          else
+#            echo "kubectl is installed!"
+#          fi
+#          kubectl version --client
+#
+#      - name: Verify Kubernetes Connection
+#        run: |
+#          echo "Checking if kubectl can connect to the cluster..."
+#          kubectl get namespaces
+#      - name: Check Pods in namespaces
+#        run: |
+#          kubectl get pods -n sh-runner
+#          kubectl get pods -n atlas
+#      - name: Set atlas image
+#        run: |
+#          echo "Updating StatefulSet 'atlas' with image: ${{ env.IMAGE_TAG }}"
+#          kubectl set image statefulset/atlas -n atlas atlas-main=${{ env.IMAGE_TAG }}
+#
+#  wait-for-deployment:
+#    needs: set-image-tag
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Get commit ID
+#        run: echo "COMMIT_ID=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
+#
+#      - name: Wait for Matching Revision
+#        run: |
+#          MAX_RETRIES=30  # Set maximum number of retries
+#          SLEEP_TIME=60  # Time in seconds between retries
+#
+#          for i in $(seq 1 $MAX_RETRIES); do
+#              echo "Attempt $i: Checking API for matching commit ID..."
+#
+#              REVISION=$(curl --silent --location 'https://gcpotel.atlan.com/api/meta/admin/version' \
+#                --header "Authorization: Bearer $(curl --silent --location 'https://gcpotel.atlan.com/auth/realms/default/protocol/openid-connect/token' \
+#                  --header 'Content-Type: application/x-www-form-urlencoded' \
+#                  --data-urlencode 'client_id=atlan-argo' \
+#                  --data-urlencode 'grant_type=client_credentials' \
+#                  --data-urlencode "client_secret=${{ secrets.ATLAN_ARGO_CLIENT_SECRET }}" | jq -r '.access_token')" | jq -r '.Revision' | cut -c1-7)
+#
+#              echo "Fetched Revision: $REVISION"
+#              echo "Expected Commit ID: ${{ env.COMMIT_ID }}"
+#              if [[ "$REVISION" == "${{ env.COMMIT_ID }}" ]]; then
+#                  echo "✅ Revision matches commit ID! Proceeding to the next step..."
+#                  exit 0
+#              fi
+#              echo "🔄 No match yet. Retrying in $SLEEP_TIME seconds..."
+#              sleep $SLEEP_TIME
+#          done
+#          echo "❌ ERROR: Max retries reached. Commit ID did not match the revision."
+#          exit 1
   setup-java-sdk:
     runs-on: ubuntu-latest
     steps:
@@ -223,12 +225,26 @@ jobs:
       - name: List integration tests
         id: test-files
         run: |
-          tests=$(ls integration-tests/src/test/java/com/atlan/java/sdk/*Test.java | sed -E 's|.*/src/test/java/com/atlan/java/sdk/||; s|/|.|g; s|\.java$||' | tr '\n' ' ')
+          # Pattern of test files to skip (modify as desired).
+          # If your files are strictly named File1Test.java, File2Test.java, etc.,
+          # make sure to match them correctly below.
+          SKIP_PATTERN="SearchTest.java|RequestsTest.java|ResourceTest.java|SSOTest.java|WorkFlowTest.java"
+
+          # List all *Test.java files, exclude the ones that match SKIP_PATTERN
+          tests=$(ls integration-tests/src/test/java/com/atlan/java/sdk/*Test.java \
+            | grep -vE "${SKIP_PATTERN}" \
+            | sed -E 's|.*/src/test/java/com/atlan/java/sdk/||; s|/|.|g; s|\.java$||' \
+            | tr '\n' ' ')
+
+          # Convert the space-separated test list into JSON array
           json_tests=$(echo "$tests[@]}" | jq -R -c 'split(" ")[:-1]')
+
+          # Output for use in later jobs
           echo "tests=$json_tests" >> $GITHUB_OUTPUT
+
   integration-test:
     needs:
-      - wait-for-deployment
+#      - wait-for-deployment
       - setup-java-sdk
       - list-integration-tests
     runs-on: ubuntu-latest
